# Generated by Django 4.1.3 on 2022-11-30 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellidos", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                ("fecha_defuncion", models.DateField(blank=True, null=True)),
                ("biografia", models.TextField()),
                ("imagen", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("idioma_original", models.CharField(max_length=30)),
                ("fecha_lanzamiento", models.DateField()),
                ("descripcion", models.TextField()),
                ("imagen", models.ImageField(upload_to="")),
                ("duracion", models.IntegerField()),
                (
                    "director",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.director",
                    ),
                ),
            ],
        ),
    ]
